import { MenuItem, Review } from "./types";

export const MENU_ITEMS: MenuItem[] = [
  // PIZZA AL METRO CONTROLLER KEY ITEMS (Keep these pristine for user customization flow!)
  {
    id: "metro-mezzo",
    name: "Mezzo Metro di Pizza (50cm)",
    description: "Perfetto per 2 persone. Impasto soffice ad alta idratazione con 72 ore di lievitazione naturale. Seleziona fino a 2 gusti a scelta dalle nostre specialità.",
    price: 14.00,
    category: "pizza-metro",
    tags: ["Ideale per 2", "Gusti Personalizzabili", "Specialità della Casa"],
  },
  {
    id: "metro-intero",
    name: "Un Metro Intero di Pizza (100cm)",
    description: "La nostra leggendaria pizza al metro, ideale per 3-4 persone. Seleziona fino a 3 gusti a scelta. Leggera, digeribile e fragrante.",
    price: 28.00,
    category: "pizza-metro",
    tags: ["Ideale per Famiglie/Gruppi", "Fino a 3 Gusti", "Bordo Soffice SF"],
  },

  // MENÙ PROMO
  {
    id: "menu-famiglia",
    name: "Menù Famiglia",
    description: "Festa per 4 persone: scegli 4 pizze classiche/rosse a scelta, 4 porzioni di patatine fritte croccanti o chips fatte in casa e 4 bibite analcoliche o birre in lattina.",
    price: 48.00,
    category: "menu",
    tags: ["Ideale per 4", "Miglior Prezzo"],
  },
  {
    id: "menu-single",
    name: "Menù Single",
    description: "La tua pausa perfetta: scegli 1 pizza a scelta dalle classiche, 1 porzione di patatine o chips rustiche e 1 bibita rinfrescante o birra 33cl.",
    price: 13.00,
    category: "menu",
    tags: ["Solo per te"],
  },
  {
    id: "menu-coppia",
    name: "Menù Coppia",
    description: "Cena per due: seleziona 2 pizze classiche o rosse a scelta, 2 porzioni di patatine fritte o chips dorate e 2 bibite o birre a scelta.",
    price: 25.00,
    category: "menu",
    tags: ["Promo Coppia"],
  },

  // PIZZE ROSSE (Base Pomodoro)
  {
    id: "rossa-salsiccia",
    name: "Salsiccia",
    description: "Pomodoro San Marzano DOP, fior di latte filante e saporita salsiccia fresca sbriciolata.",
    price: 9.00,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-napoli",
    name: "Alla Napoli (Napolitana)",
    description: "Pomodoro, fior di latte locale, acciughe sapide dell'Adriatico e capperi selezionati.",
    price: 8.50,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-affumicata",
    name: "Affumicata",
    description: "Pomodoro, mozzarella, profumata mortadella di Bologna e provola/scamorza affumicata calda.",
    price: 9.00,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-parmigiana",
    name: "Alla Parmigiana",
    description: "Pomodoro, mozzarella e la nostra parmigiana di melanzane fatta in casa saporitissima.",
    price: 9.50,
    category: "pizze-rosse",
    isAvailableForMetro: true,
    tags: ["Consigliata"],
  },
  {
    id: "rossa-bufala",
    name: "Bufala",
    description: "Pomodoro San Marzano e squisita mozzarella di bufala campana DOP filante in cottura.",
    price: 10.00,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-margherita",
    name: "Margherita",
    description: "Il grande classico intramontabile: pomodoro San Marzano DOP, fior di latte locale e olio EVO.",
    price: 6.50,
    category: "pizze-rosse",
    isAvailableForMetro: true,
    tags: ["Best Seller"],
  },
  {
    id: "rossa-paperina",
    name: "Paperina",
    description: "Pomodoro, mozzarella, wurstel bavaresi a fette e montagna di patatine fritte dorate.",
    price: 8.50,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-crudo",
    name: "Al Crudo",
    description: "Pomodoro, mozzarella fior di latte, prosciutto crudo di Parma dolce, pomodorini Pachino succosi e scaglie di grana.",
    price: 10.00,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-marinella",
    name: "Marinella (Marinara)",
    description: "Raffinata semplicità: pomodoro San Marzano, fettine di aglio rosso fresco, origano selvatico del Gargano e olio EVO.",
    price: 5.00,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-cotto-funghi",
    name: "Cotto e Funghi",
    description: "Pomodoro morbido, fior di latte, prosciutto cotto di alta qualità e funghi champignon freschi trifolati.",
    price: 9.50,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },
  {
    id: "rossa-diavola",
    name: "Diavola",
    description: "Pomodoro San Marzano, mozzarella e salamino piccante pugliese artigianale a fette.",
    price: 9.50,
    category: "pizze-rosse",
    isAvailableForMetro: true,
    tags: ["Piccante"],
  },
  {
    id: "rossa-parma",
    name: "Parma d'Autore",
    description: "Pomodoro, mozzarella, prosciutto crudo di Parma, mozzarella di bufala fresca aggiunta fuori cottura e panna vellutata.",
    price: 11.00,
    category: "pizze-rosse",
    isAvailableForMetro: true,
  },

  // PIZZE BIANCHE
  {
    id: "bianca-spianata",
    name: "Spianata Bianca (Focaccia)",
    description: "Focaccia tradizionale con spolverata generosa di origano selvatico e filo d'olio d'oliva delle nostre colline.",
    price: 5.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-otto-formaggi",
    name: "La 8 Formaggi",
    description: "Sinfonia di formaggi: Mozzarella, cacio foggiano, gorgonzola dolce, bufala, provolone, scamorza affumicata, ricotta di bufala e mozzarelline fresche di Deliceto.",
    price: 11.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
    tags: ["Specialità"],
  },
  {
    id: "bianca-crudaiola",
    name: "Crudaiola",
    description: "Base spianata cotta abbinata fuori cottura a pomodorini datterini freschi, mozzarella di bufala cruda a fette e rucola fresca.",
    price: 9.50,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-amalfi",
    name: "Amalfi",
    description: "Abbinamento sublime: mozzarella fiordilatte locale, mozzarella di bufala a freddo e scorzetta di limone grattugiata fresca.",
    price: 10.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
    tags: ["Fresco"],
  },
  {
    id: "bianca-carbonara",
    name: "Carbonara",
    description: "Mozzarella fiordilatte, guanciale laziale artigianale croccante, uovo fresco mantecato e profumato pecorino romano DOP.",
    price: 10.50,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-capricciosa",
    name: "Capricciosa Bianca",
    description: "Base bianca con fior di latte, prosciutto cotto, funghi trifolati, olive nere, peperoni dolci e carciofini pugliesi sott'olio.",
    price: 9.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-mortazza",
    name: "Mortazza",
    description: "Mozzarella fiordilatte, scaglie di cacio locale, mortadella IGP, grana padano, rucola selvatica e glassa di aceto balsamico.",
    price: 10.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-martina",
    name: "La Martina",
    description: "Base mozzarella, pregiato capocollo di Martina Franca a fette, miele biologico e generosa stracciatella di bufala foggiana.",
    price: 12.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
    tags: ["Assolutamente da Provare"],
  },
  {
    id: "bianca-speck-tartufo",
    name: "Speck e Tartufo",
    description: "Abbinamento intenso: mozzarella filante, pregiato speck tirolese e crema profumata di tartufo nero.",
    price: 12.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-vegetariana",
    name: "La Vegetariana",
    description: "Fior di latte, melanzane e zucchine grigliate alla brace, peperoni dolci e pomodori Pachino freschi.",
    price: 9.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
    tags: ["Vegetariana"],
  },
  {
    id: "bianca-tonno",
    name: "Tonno della Casa",
    description: "Base bianca con fior di latte, filetti di tonno sott'olio della costa, cipolla rossa affettata fine e pomodori Pachino dolci.",
    price: 9.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-quattro-formaggi",
    name: "La Quattro Formaggi",
    description: "Mozzarella fiordilatte, gorgonzola cremoso dop, provolone dolce e formaggi misti fusi in forno.",
    price: 9.50,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-salsiccia-patate",
    name: "Salsiccia Bianca",
    description: "Mozzarella fior di latte, salsiccia fresca a punta di coltello e patate novelle al rosmarino tagliate sottili.",
    price: 9.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-speck-scamorza",
    name: "Speck",
    description: "Base bianca con fior di latte locale, speck aromatico e scamorza affumicata in legno di faggio.",
    price: 9.50,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-capocollo-gorgo",
    name: "Capocollo e Gorgonzola",
    description: "Sapori forti: fior di latte filante, ottimo capocollo tipico e sfumature di gorgonzola DOP piccante.",
    price: 9.50,
    category: "pizze-bianche",
    isAvailableForMetro: true,
  },
  {
    id: "bianca-gustosa",
    name: "Gustosa",
    description: "Squisitezza assoluta: mozzarella fiordilatte, pesto di pistacchi di Bronte, mortadella profumata a fette sottili e cucchiaiate di stracciatella fresca.",
    price: 11.00,
    category: "pizze-bianche",
    isAvailableForMetro: true,
    tags: ["Super Consigliata"],
  },

  // CALZONI
  {
    id: "calzone-nostrano",
    name: "Calzone Nostrano",
    description: "Calzone ripieno cotto al forno con pomodoro San Marzano, mozzarella fior di latte, ricotta vaccina fresca e salamino piccante.",
    price: 12.00,
    category: "calzoni",
  },
  {
    id: "calzone-esagerato",
    name: "Calzone Esagerato",
    description: "Dedicato ai buongustai: pomodoro, mozzarella fiordilatte, prosciutto cotto gustoso, rucola condita, salamino piccante e pomodorini Pachino succosi.",
    price: 12.00,
    category: "calzoni",
    tags: ["Giga Ripieno"],
  },

  // PAPOSCE (Il tipico panino del Gargano cotto a forno a legna)
  {
    id: "paposcia-parmigiana",
    name: "Paposcia Parmigiana",
    description: "Pane paposcia del Gargano croccante farcito con parmigiana di melanzane alla foggiana e scamorza affumicata filante.",
    price: 10.50,
    category: "paposce",
    tags: ["Tradizione Garganica"],
  },
  {
    id: "paposcia-pugliese",
    name: "Paposcia Pugliese",
    description: "Farcitura sublime: zucchine grigliate dolci, capocollo nostrano, formaggio fresco primo sale e un tocco di miele d'arancia profumato.",
    price: 10.50,
    category: "paposce",
  },

  // STRACCETTI DI PASTA COMPOSITIONS
  {
    id: "straccetto-atomico",
    name: "Straccetto Atomico",
    description: "Bocconcini dorati di pasta fritta conditi con pomodoro San Marzano saporito, prosciutto crudo di Parma a pezzetti sfiziosi, mozzarella di bufala sfilacciata e rucola.",
    price: 11.00,
    category: "straccetti",
    tags: ["Specialità Furia"],
  },
  {
    id: "straccetto-classico",
    name: "Straccetto Classico",
    description: "Semplice e delizioso: straccetti caldi di pasta lievitata conditi all'uscita semplicemente con eccellente olio EVO, sale fine e origano.",
    price: 8.00,
    category: "straccetti",
  },
  {
    id: "straccetto-caponata",
    name: "Straccetto Caponata",
    description: "Impasto di pizza caldo saltato con un misto di saporite verdure di stagione grigliate ed insaporite con olio extravergine d'oliva.",
    price: 10.00,
    category: "straccetti",
  },

  // CALZONE SPECIALE AL FORNO (Maxi Panzerotti)
  {
    id: "panzerotto-ricotta",
    name: "Maxi Panzerotto con Ricotta e Salamino Piccante",
    description: "Maestoso e fragrante panzerotto al forno ripieno di ricotta vaccina fresca mantecata al pepe e fettine saporite di salame piccante.",
    price: 10.00,
    category: "calzone-speciale-forno",
  },
  {
    id: "panzerotto-pomodoro",
    name: "Maxi Panzerotto con Pomodoro e Mozzarella",
    description: "Il supremo panzerotto al forno della tradizione: ripieno ricco di passata San Marzano dop e dadini abbondanti di fior di latte locale.",
    price: 10.00,
    category: "calzone-speciale-forno",
  },
  {
    id: "panzerotto-cotto",
    name: "Maxi Panzerotto con Prosciutto Cotto e Mozzarella",
    description: "Farcito con prosciutto cotto d'Abruzzo di alta qualità e fior di latte locale filante, cotto lentamente al forno.",
    price: 10.00,
    category: "calzone-speciale-forno",
  },
  {
    id: "panzerotto-mortazza",
    name: "Maxi Panzerotto con Mortadella e Cacio",
    description: "Sapore antico: maxi panzerotto sfornato caldissimo ripieno di profumata mortadella Bologna e scaglie di cacio foggiano saporito.",
    price: 10.00,
    category: "calzone-speciale-forno",
  },

  // ANTIPASTI
  {
    id: "anti-parmigiana",
    name: "Parmigiana di Melanzane",
    description: "Melanzane fritte ricoperte di pomodoro denso, fior di latte, basilico e grana, cotta e dorata in forno.",
    price: 8.00,
    category: "antipasti",
  },
  {
    id: "anti-salumi",
    name: "Degustazione Salumi Tipici",
    description: "Selezione ricercata dei migliori salumi artigianali della Capitanata e della Puglia interna conditi con olive.",
    price: 14.00,
    category: "antipasti",
    tags: ["Consigliato per Due"],
  },
  {
    id: "anti-cacio-speck",
    name: "Cacio in Terrina con Speck e Tartufo",
    description: "Formaggio cacio locale fuso nel tegame in terracotta guarnito con croccante speck affumicato e crema vellutata di tartufo nero.",
    price: 8.50,
    category: "antipasti",
    tags: ["Caldo & Saporito"],
  },
  {
    id: "anti-formaggi",
    name: "Degustazione Formaggi Tipici",
    description: "Formaggi pugliesi d'eccellenza, freschi e stagionati, serviti con miele d'api e mostarda.",
    price: 14.00,
    category: "antipasti",
  },
  {
    id: "anti-misto-tagliere",
    name: "Degustazione Misto con Salumi e Formaggi",
    description: "Gran tagliere imperiale per condividere i migliori formaggi e salumi della nostra terra.",
    price: 18.00,
    category: "antipasti",
    tags: ["Imperiale"],
  },
  {
    id: "anti-casa",
    name: "Antipasti da Antonello",
    description: "Il nostro antipasto fantasia composto da prelibatezze miste calde e fredde dello chef.",
    price: 16.00,
    category: "antipasti",
  },
  {
    id: "anti-bruschetta",
    name: "Bruschetta Classica",
    description: "Fette spesse di pane rustico tostato sulla brace condite con pomodorini datterini, aglio novello tritato, origano e profumato olio EVO.",
    price: 5.00,
    category: "antipasti",
  },
  {
    id: "anti-cacio",
    name: "Cacio in Terrina",
    description: "Semplice e filante sformato di formaggio cacio fuso in forno di terracotta calda.",
    price: 8.00,
    category: "antipasti",
  },
  {
    id: "anti-mortadella-brace",
    name: "Mortadella alla Brace",
    description: "Taglio spesso di mortadella Bologna IGP grigliata lentamente alla griglia per un sapore caramellato sublime.",
    price: 8.00,
    category: "antipasti",
  },
  {
    id: "anti-crudo-bufala",
    name: "Prosciutto Crudo e Mozzarella di Bufala",
    description: "Soffice e freschissima mozzarella di bufala pugliese (250g) affiancata da prosciutto crudo di Parma stagionato.",
    price: 9.00,
    category: "antipasti",
  },
  {
    id: "anti-bresaola",
    name: "Bresaola, Rucola e Grana",
    description: "Petali di fassona bresaola guarniti con fresca rucola selvatica di collina e scaglie generose di grana riserva.",
    price: 10.00,
    category: "antipasti",
  },

  // ANTIPASTI DI MARE
  {
    id: "anti-polpo-carpaccio",
    name: "Carpaccio di polpo",
    description: "Fettine finissime di polpo verace cotto condite delicatamente con olio extravergine d'oliva, gocce di limone e prezzemolo fresco.",
    price: 15.00,
    category: "antipasti-di-mare",
  },
  {
    id: "anti-polpo-patate",
    name: "Insalata di polpo e patate",
    description: "Arricchito antipasto della costa con polpo fresco tenero, patate lesse a cubetti, sedano croccante, limone pugliese e olio EVO.",
    price: 16.00,
    category: "antipasti-di-mare",
    tags: ["Tradizione di Mare"],
  },

  // PRIMI DI TERRA
  {
    id: "primo-orecchiette-tri",
    name: "Orecchiette tricolore",
    description: "La freschezza in tavola: orecchiette tradizionali saltate con pomodorini dolci, dadini di bufala campana a freddo e rucola fresca.",
    price: 10.00,
    category: "primi-di-terra",
  },
  {
    id: "primo-orecchiette-salsiccia",
    name: "Orecchiette Salsiccia e Verdura di Stagione",
    description: "Classico foggiano con orecchiette saltate con salsiccia sgranata sfumata al vino bianco e verdure di stagione selvatiche (come cime di rapa o friarielli).",
    price: 10.00,
    category: "primi-di-terra",
    tags: ["Fatto a Mano"],
  },
  {
    id: "primo-paccheri-porcini",
    name: "Paccheri salsiccia e funghi porcini",
    description: "Paccheri di grano duro saltati con sugo ricco di salsiccia fresca di maiale e profumati funghi porcini raccolti sui nostri monti.",
    price: 12.00,
    category: "primi-di-terra",
  },
  {
    id: "primo-paccheri-sicula",
    name: "Paccheri alla Sicula",
    description: "Sugo di pomodoro verace, melanzane fritte deliziose, grattugiata copiosa di ricotta salata forte e basilico.",
    price: 10.00,
    category: "primi-di-terra",
  },
  {
    id: "primo-paccheri-norcia",
    name: "Paccheri crema di melanzane guanciale di Norcia stracciatella e noci",
    description: "Piatto gourmet con paccheri avvolti in crema di melanzane, guanciale di Norcia croccante, stracciatella fresca e gherigli di noci tritate.",
    price: 12.00,
    category: "primi-di-terra",
    tags: ["Gourmet"],
  },
  {
    id: "primo-orecchiette-pesto",
    name: "Orecchiette Pesto di Pistacchio e Mortadella",
    description: "Squisite orecchiette calde mantecate con pesto puro di pistacchio di Bronte e arricchite con listarelle di mortadella Bologna grigliate.",
    price: 10.00,
    category: "primi-di-terra",
  },
  {
    id: "primo-paccheri-speck",
    name: "Paccheri Porcini, Speck e Tartufo",
    description: "Intenso connubio cremoso di paccheri trafilati al bronzo con porcini, speck croccante saporito e olio al tartufo nero d'Abruzzo.",
    price: 10.00,
    category: "primi-di-terra",
  },

  // PRIMI DI MARE
  {
    id: "primo-troccoli-scoglio",
    name: "Troccoli allo Scoglio",
    description: "Pasta troccoli tipica fresca condita con un eccellente sugo ricco di cozze, vongole, gamberi freschi e calamari saltati con aroma d'aglio.",
    price: 15.00,
    category: "primi-di-mare",
    tags: ["Adriatico Fresco"],
  },
  {
    id: "primo-spaghettoni-vongole",
    name: "Spaghettone con Vongole e Lime",
    description: "Spaghettone ruvido risottato in bianco con vongole veraci fresche sgusciate e intere, rinfrescate con scorzetta di lime grattugiata.",
    price: 15.00,
    category: "primi-di-mare",
  },
  {
    id: "primo-orecchiette-crema",
    name: "Orecchiette con Crema di Patate e Gamberi",
    description: "Ricetta creativa di orecchiette racchiuse in una liscia crema di patate mantecate con gamberi reali saltati ed sfumati.",
    price: 15.00,
    category: "primi-di-mare",
  },

  // SECONDI DI TERRA
  {
    id: "secondo-manzo-mille",
    name: "Millefoglie di Manzo con Funghi Porcini, Rucola e Grana",
    description: "Sottili sfoglie di tenerissimo manzo scottato alla piastra alternate a funghi porcini trifolati caldi, rucola selvatica di collina e scaglie di grana padano.",
    price: 19.00,
    category: "secondi-di-terra",
    tags: ["Piatto Forte"],
  },
  {
    id: "secondo-pollo-limone",
    name: "Scaloppina di Pollo al Limone",
    description: "Scaloppina tenera di petto di pollo cotta con burro chiarito d'alpeggio e succo di limone fresco spremuto al momento.",
    price: 12.00,
    category: "secondi-di-terra",
  },
  {
    id: "secondo-manzo-gorgo",
    name: "Manzo con Vino Rosso e Gorgonzola",
    description: "Tenerissimo girello di manzo tagliato sottile scaloppato con riduzione corposa di vino Nero di Troia e formaggio gorgonzola fuso.",
    price: 17.00,
    category: "secondi-di-terra",
  },
  {
    id: "secondo-manzo-pepe",
    name: "Manzo al Pepe Verde",
    description: "Medaglione di manzo pregiato cucinato in padella con sfumatura di brandy e salsa setosa al pepe verde aromatico.",
    price: 17.00,
    category: "secondi-di-terra",
  },
  {
    id: "secondo-pollo-balsamico",
    name: "Straccetti di Pollo al Balsamico",
    description: "Straccetti di petto di pollo cotti velocemente alla piastra con glassa di aceto balsamico di Modena invecchiato siracusano.",
    price: 12.00,
    category: "secondi-di-terra",
  },
  {
    id: "secondo-cotoletta",
    name: "Cotoletta e Patatine",
    description: "Cotoletta di pollo fresca panata a mano croccante, servita calda con contorno gigante di patatine fritte dorate.",
    price: 11.00,
    category: "secondi-di-terra",
  },
  {
    id: "secondo-scaloppina-vino",
    name: "Scaloppina di Pollo al Vino Bianco",
    description: "Tenero petto di pollo battuto e spadellato con una deliziosa riduzione aromatica di vino bianco secco.",
    price: 12.00,
    category: "secondi-di-terra",
  },
  {
    id: "secondo-scaloppina-porcini",
    name: "Scaloppina di Pollo ai Funghi Porcini",
    description: "Scaloppina morbidissima cotta in padella con un sugo ristretto di squisiti funghi porcini del territorio.",
    price: 12.00,
    category: "secondi-di-terra",
  },

  // SECONDI DI MARE
  {
    id: "secondo-frittura-mista",
    name: "Frittura Totani con Seppie e Gamberetti",
    description: "Gran frittura mista fella casa fragrante, asciutta e dorata, con anelli di totano, seppioline nostrane e gamberi dal sapore dolce.",
    price: 18.00,
    category: "secondi-di-mare",
    tags: ["Fritto Perfetto"],
  },
  {
    id: "secondo-gamberoni-curry",
    name: "Gamberoni con Pomodoro Pachino e Curry",
    description: "Succosi e carnosi gamberoni sgusciati spadellati con datterini confit, olio profumato d'aglio e spolverata esotica di curry.",
    price: 14.00,
    category: "secondi-di-mare",
  },
  {
    id: "secondo-spigola",
    name: "Spigola al Forno alla Mediterranea",
    description: "Freschissima spigola intera da circa 400 grammi cotta lentamente al cartoccio con pomodorini datterini, olive nere di Cerignola e erbe del Gargano.",
    price: 15.00,
    category: "secondi-di-mare",
  },
  {
    id: "secondo-spada-sicura",
    name: "Trancio di Pesce Spada con Olive, Capperi e Pomodorini",
    description: "Taglio fresco di pesce spada cucinato alla mediterranea con datterini succosi, capperi di pantelleria e olive denocciolate.",
    price: 16.00,
    category: "secondi-di-mare",
  },

  // BRACERIA (Carni di prima qualità)
  {
    id: "brace-bombette",
    name: "Bombette di Martina Franca",
    description: "I famosissimi involtini di capocollo di maiale farciti internamente con caciocavallo locale e prezzemolo, cotti sulla brace viva.",
    price: 12.00,
    category: "braceria",
    tags: ["Inimitabili"],
  },
  {
    id: "brace-filetto",
    name: "Filetto di Manzo alla Griglia",
    description: "Taglio pregiatissimo e morbidissimo di filetto di manzo cotto alla griglia su carboni, completato con sale grosso e rosmarino.",
    price: 21.00,
    category: "braceria",
  },
  {
    id: "brace-cuberoll",
    name: "Cuberoll di Scottona (350g)",
    description: "Squisita costata di scottona snervata e frollata con venatura di grasso squisita che si scioglie sulla brace fumante.",
    price: 18.00,
    category: "braceria",
  },
  {
    id: "brace-hamburger",
    name: "Hamburger di Manzo (300g)",
    description: "Hamburger gigante artigianale di pura carne scottona selezionata cotto sulla brace con la sua crosticina esterna saporita.",
    price: 12.00,
    category: "braceria",
  },
  {
    id: "brace-salsiccia",
    name: "Salsiccia doppia alla brace",
    description: "Saporita salsiccia a spirale della macelleria foggiana di fiducia cotta pazientemente sulla brace.",
    price: 12.00,
    category: "braceria",
  },
  {
    id: "brace-torcinelli",
    name: "Torcinelli Tipici Foggiani",
    description: "Squisitezza foggiana: 6 pezzi dei famosissimi torcinelli locali artigianali (budelline avvolte ripiene di fegato aromatico e animelle) rosolati sulla brace.",
    price: 12.00,
    category: "braceria",
    tags: ["Specialità Foggiana 100%"],
  },
  {
    id: "brace-agnello",
    name: "Crostatine di Agnello alla Brace",
    description: "Tenerissime costolette d'agnello marinate sapientemente e grigliate a fuoco vivo.",
    price: 16.00,
    category: "braceria",
  },
  {
    id: "brace-arrosto-misto",
    name: "Arrosto Misto Imperiale",
    description: "Per gli amanti della carne: un piattone composto da torcinelli foggiani, bombette pugliesi, arrosticini abruzzesi clasici, salsiccia a spirale e crostatina di agnello.",
    price: 18.00,
    category: "braceria",
    tags: ["Gran Misto"],
  },
  {
    id: "brace-fiorentina",
    name: "Bistecca alla Fiorentina (1.2Kg - Spessore XL)",
    description: "Maestoso taglio di costata fiorentina con filetto e controfiletto cotto a riga di griglia per amanti della frollatura alta.",
    price: 55.00,
    category: "braceria",
  },

  // CONTORNI
  {
    id: "contorno-insalata",
    name: "Insalata Verde Cup",
    description: "Insalate fresche miste, rucola e cetriolini affettati conditi con limone ed olio EVO delicato.",
    price: 4.00,
    category: "contorni",
  },
  {
    id: "contorno-patate-forno",
    name: "Patate al Forno Saporite",
    description: "Teglia fumante di patate novelle di Zapponeta cotte al forno con rosmarino fresco e aglio in camicia.",
    price: 5.00,
    category: "contorni",
  },
  {
    id: "contorno-verdure",
    name: "Verdure Grigliate",
    description: "Taglio fresco di zucchine campestri, melanzane e peperoni cotti alla piastra aromatizzati con aglio, prezzemolo e olio.",
    price: 6.00,
    category: "contorni",
  },
  {
    id: "contorno-verdure-padella",
    name: "Verdure Ripassate in Padella",
    description: "Bietoline o cicorie selvatiche locali ripassate vigorosamente con olio d'oliva, aglio e peperoncino.",
    price: 5.00,
    category: "contorni",
  },

  // FRITTI
  {
    id: "fritto-scagliozzi-tartu",
    name: "Scagliozzi Tartufati",
    description: "Tradizionali scagliozzi (triangolini di polenta fritta croccante) insaporiti con una colata di crema al tartufo nero d'Abruzzo.",
    price: 5.00,
    category: "fritti",
    tags: ["Assoluta Novità"],
  },
  {
    id: "fritto-scagliozzi",
    name: "Scagliozzi Classici Foggiani",
    description: "I classici intramontabili scagliozzi dorati foggiani fatti di polenta fritta dorata, serviti caldi e salati.",
    price: 4.50,
    category: "fritti",
    tags: ["Tradizione di Strada"],
  },
  {
    id: "fritto-patatine-fra",
    name: "Patatine Fritte Croccanti",
    description: "Patate a fiammifero fritte in olio di arachide pulitissimo e salate al momento.",
    price: 4.50,
    category: "fritti",
  },
  {
    id: "fritto-chips-cacio",
    name: "Chips con Cacio e Pepe",
    description: "Sfoglie di patate fatte in casa fritte dorate e spolverate caldissime con pecorino romano e macinata di pepe nero fresco.",
    price: 4.50,
    category: "fritti",
    tags: ["Gustose"],
  },
  {
    id: "fritto-chips",
    name: "Chips Classiche",
    description: "Sfoglie sottilissime e leggerissime di patate fritte rigorosamente a mano fresche.",
    price: 4.50,
    category: "fritti",
  },

  // BIRRE
  {
    id: "birra-peroni",
    name: "Peroni 33 cl",
    description: "La bionda preferita dai foggiani, fresca e dissetante.",
    price: 1.50,
    category: "birre",
    tags: ["Ghiacciata"],
  },

  // BEVANDE ANALCOLICHE
  {
    id: "bevanda-acqua-nat",
    name: "Acqua Naturale (1.5L)",
    description: "Bottiglia di acqua naturale minerale locale.",
    price: 2.00,
    category: "bevande",
  },
  {
    id: "bevanda-acqua-frizzy",
    name: "Acqua Frizzante (1.5L)",
    description: "Bottiglia di acqua minerale gassata fresca.",
    price: 2.00,
    category: "bevande",
  },
  {
    id: "bevanda-coca-33",
    name: "Coca Cola in Bottiglia 33cl",
    description: "Classica bottiglia in vetro per preservare il sapore originale freddo.",
    price: 2.50,
    category: "bevande",
  },
  {
    id: "bevanda-cocazero-33",
    name: "Coca Cola Zero in Bottiglia 33cl",
    description: "Tutto il gusto originale della Coca Cola senza zuccheri in bottiglia di vetro.",
    price: 2.50,
    category: "bevande",
  },
  {
    id: "bevanda-fanta-33",
    name: "Fanta in Bottiglia 33cl",
    description: "Aranciata frizzante in bottiglietta di vetro fresca.",
    price: 2.50,
    category: "bevande",
  },
  {
    id: "bevanda-sprite-33",
    name: "Sprite in Bottiglia 33cl",
    description: "Gusto limone e lime rinfrescante in vetro.",
    price: 2.50,
    category: "bevande",
  },
  {
    id: "bevanda-chino",
    name: "Bibita 33cl bottiglia - Chinò",
    description: "L'originale chinotto amaro Sanpellegrino in vetro.",
    price: 2.00,
    category: "bevande",
  },

  // DOLCI
  {
    id: "dolce-cannolo",
    name: "Cannolo scomposto con Ricotta al pistacchio",
    description: "Cialda di cannolo croccante sbriciolata servita in bicchiere con morbida ricotta pugliese dolce ed un pesto dolce di pistacchio puro.",
    price: 5.00,
    category: "dolci",
    tags: ["Fatto in Casa"],
  },
  {
    id: "dolce-cheesecake-berry",
    name: "Cheesecake ai Frutti di Bosco",
    description: "Golosa cheesecake fredda ricoperta con salsa artigianale di more, lamponi e mirtilli di bosco.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-tiramisu",
    name: "Tiramisù Classico",
    description: "Tiramisù casalingo secondo la ricetta della mamma: mascarpone, uova fresche, savoiardi inzuppati nel caffè espresso bollente.",
    price: 5.00,
    category: "dolci",
    tags: ["Cremoso"],
  },
  {
    id: "dolce-cestino-bosco",
    name: "Cestino di sfoglia crema e frutti di bosco",
    description: "Cestino di friabile pasta sfoglia fatto a mano ricolmo di crema pasticcera densa e lamponi/more fresche.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-cestino-amarene",
    name: "Cestino di sfoglia crema e amarene",
    description: "Friabile cestino riempito con crema calda pasticcera e amarene candite intere nel loro denso sciroppo.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-cheesecake-nutella",
    name: "Cheesecake alla Nutella",
    description: "Base croccante di biscotto ricoperto con ripieno morbido e sovrastato da un generoso strato vellutato di Nutella Ferrero.",
    price: 5.00,
    category: "dolci",
    tags: ["Amato dai Bambini"],
  },
  {
    id: "dolce-sbriciolata",
    name: "Coppa Sbriciolata con Nutella",
    description: "Dessert al cucchiaio con strati di biscotti friabili sbriciolati, velluto di crema pasticcera e collate calde di Nutella.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-cheesecake-amarena",
    name: "Cheesecake all'Amarena",
    description: "Dolce di crema fresco decorato sulla parte superiore con sciroppo denso e amarene selvatiche sciroppate.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-millefoglie",
    name: "Millefoglie Chantilly e amarene",
    description: "Sfoglie sottilissime e burrose alternate a nuvole di fresca crema chantilly e amarene selvatiche candite.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-cestino-nutella",
    name: "Cestino di sfoglia crema e nutella",
    description: "Friabile pasta sfoglia riempita all'istante con crema pasticcera profumata all'arancio e guarnita con Nutella.",
    price: 5.00,
    category: "dolci",
  },
  {
    id: "dolce-cheesecake-pista",
    name: "Cheesecake al Pistacchio",
    description: "Cheesecake fredda ricoperta con una voluttuosa glassa lucida al pistacchio dolce fuso.",
    price: 5.00,
    category: "dolci",
  },

  // COCKTAILS
  {
    id: "cocktail-negroni",
    name: "Negroni",
    description: "La miscela iconica con Gin dry italiano, Campari rosso amaro e Vermouth rosso, guarnita con fetta d'arancia.",
    price: 5.00,
    category: "cocktail",
  },
  {
    id: "cocktail-negroni-sba",
    name: "Negroni Sbagliato",
    description: "Al posto del gin, prosecco brut spumante miscelato con Campari amaro e dolce Vermouth rosso.",
    price: 5.00,
    category: "cocktail",
  },
  {
    id: "cocktail-gin-lemon",
    name: "Gin Lemon",
    description: "Gin dry premium unito con bibita Schweppes lemon fresca e spremi di agrume.",
    price: 5.00,
    category: "cocktail",
  },
  {
    id: "cocktail-gin-tonic",
    name: "Gin Tonic",
    description: "Il distillato preferito dai giovani miscelato con ottima acqua tonica amara, servito in calice ballon ghiacciato.",
    price: 5.00,
    category: "cocktail",
  },
  {
    id: "cocktail-spritz",
    name: "Spritz Aperol",
    description: "Aperitivo veneziano di gran moda: Aperol aranciato scuro, spumante Prosecco frizzante doc, soda ed fettina.",
    price: 5.00,
    category: "cocktail",
    tags: ["Aperitivo Cult"],
  },

  // VINI ROSSI
  {
    id: "vino-kandea-nero",
    name: "Kandea Nero di Troia",
    description: "Vino rosso eccellente delle cantine foggiane Kandea, profumi di more e prugne mature, sapore avvolgente secco.",
    price: 17.00,
    category: "vini-rossi",
  },
  {
    id: "vino-barbaresco",
    name: "Barbaresco Montersino",
    description: "Un signore dei vini piemontesi, affinato sapientemente con splendide note tostate e speziate di ciliegia.",
    price: 40.00,
    category: "vini-rossi",
    tags: ["Pregiato"],
  },
  {
    id: "vino-amarone",
    name: "Amarone Della Valpollicella",
    description: "Regale vino passito secco veneto dotato di corposità vellutata e calore persistente.",
    price: 76.00,
    category: "vini-rossi",
    tags: ["Esclusivo"],
  },
  {
    id: "vino-dolcetto",
    name: "Dolcetto d'alba",
    description: "Rosso Doc d'Alba piemontese, fresco e fruttato, beverino con retrogusto di mandorla dolce.",
    price: 18.00,
    category: "vini-rossi",
  },
  {
    id: "vino-primitivo",
    name: "W'heart Primitivo",
    description: "Primitivo del tarantino di eccellente beva, sentori caldi di marmellata di ciliegie e carrube.",
    price: 16.00,
    category: "vini-rossi",
  },
  {
    id: "vino-montepulciano",
    name: "Strapelli montepulciano",
    description: "Rosso abruzzese potente, corposo con morbidezza data da lunghe maturazioni in bottiglia.",
    price: 18.00,
    category: "vini-rossi",
  },
  {
    id: "vino-aglianico",
    name: "Kandea Aglianico",
    description: "Pregiato Aglianico vinificato nel Tavoliere delle Puglie, con tannino presente ma levigato.",
    price: 15.00,
    category: "vini-rossi",
  },
  {
    id: "vino-barbera",
    name: "Barbera",
    description: "Vino piemontese tipico d'eccellenza, spiccata freschezza succosa, abbinamento ideale.",
    price: 29.00,
    category: "vini-rossi",
  },
  {
    id: "vino-susumaniello",
    name: "Masseria Li Veli Susumaniello",
    description: "Straordinario vitigno autoctono pugliese vinificato in rosso, sentori marini di pepe nero e ciliegia scura.",
    price: 17.00,
    category: "vini-rossi",
  },
  {
    id: "vino-barolo",
    name: "Barolo Mirau",
    description: "Maestoso vino rosso Barolo docg nobile e austero affinato in grandi botti di rovere.",
    price: 58.00,
    category: "vini-rossi",
    tags: ["Re dei Vini"],
  },

  // VINI ROSATI
  {
    id: "rosato-pruina",
    name: "La Pruina Negroamaro Rosato",
    description: "Splendido rosato fresco del Salento con intense note di lampone, melograno e freschezza salina.",
    price: 15.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-dammirose",
    name: "Dammirose Rosato",
    description: "Rosato pugliese d'eccezione, fresco ed equilibratissimo, note ciliegia.",
    price: 12.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-dommirose-nero",
    name: "Dommirose Nero di Troia Rosato",
    description: "Un'espressione rosa cristallina del vitigno re del Tavoliere, sentori floreali selvatici.",
    price: 14.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-ca-dei-frati",
    name: "Rosa dei Frati",
    description: "Celebre vino rosa lombarda sponda sud del Garda, elegante ed profumatissimo.",
    price: 17.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-marilina-bio",
    name: "Marilina Nero di Troia Rosato",
    description: "Vino rosato biologico fresco, sapido, dal bouquet elegante di petali di rosa selvatica e pepe bianco.",
    price: 18.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-imprint-susu",
    name: "Imprint Susumaniello Rosato",
    description: "Rosato salentino intrigante con piacevolissime sfumature fruttate dolci ed un finale fresco persistente.",
    price: 14.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-attanasio",
    name: "Le Vigne di Attanasio Primitivo Rosato",
    description: "Pregiato rosato denso da uve primitivo raccolte in vendemmia anticipate, frutti rossi croccanti.",
    price: 18.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-triglia",
    name: "Triglia Negroamaro",
    description: "Rosato fresco, sapido e vibrante della cantina d'autore salentina.",
    price: 20.00,
    category: "vini-rosati",
  },
  {
    id: "bianco-ca-dei-frati-lugana",
    name: "Ca dei Frati Lugana Doc",
    description: "Vino bianco italiano famosissimo del Garda, mineralità eccellente e grande freschezza fruttata.",
    price: 17.00,
    category: "vini-rosati",
  },
  {
    id: "rosato-donnadele",
    name: "Donnadele Rosato",
    description: "Raffinatissimo vino rosato pugliese, dal colore buccia di cipolla, bouquet fragrante di piccoli frutti.",
    price: 15.00,
    category: "vini-rosati",
  },

  // VINI BIANCHI
  {
    id: "vino-falanghina-fossette",
    name: "Le fossette falanghina",
    description: "Vino bianco dauno della prestigiosa cantina Alberto Longo, profumo intenso fiorito e gran freschezza.",
    price: 17.00,
    category: "vini-bianchi",
    tags: ["Consigliato"],
  },
  {
    id: "vino-falanghina-omo",
    name: "Omo falanghina",
    description: "Vino bianco d'autore di notevole sapidità agrumata ideale in abbinamento con pizze di mare.",
    price: 16.00,
    category: "vini-bianchi",
  },
  {
    id: "vino-fiano-bianco",
    name: "Biancofiore Fiano",
    description: "Elegante vino bianco fiano pugliese, note fiorite fresche e beva asciutta salina.",
    price: 16.00,
    category: "vini-bianchi",
  },
  {
    id: "vino-ca-frati-i-frati",
    name: "I frati Lugana Bianco",
    description: "Pregiatissimo bianco Lugana dop di straordinario spessore gustoso e potenziale d'invecchiamento.",
    price: 17.00,
    category: "vini-bianchi",
  },

  // BOLLICINE (Spumanti & Metodo Classico)
  {
    id: "bolla-akenta-sub",
    name: "Akenta sub (Affinato in Mare)",
    description: "Straordinario e unico spumante vermentino di Sardegna sottomarino affinato a 40m di profondità sotto le acque calde sarde.",
    price: 58.00,
    category: "bollicine",
    tags: ["Rarissimo"],
  },
  {
    id: "bolla-centofate",
    name: "Centofate Metodo Classico",
    description: "Pregiatissimo spumante metodo classico da uve Bombino e Fiano pugliesi, bolla cremosa persistente.",
    price: 30.00,
    category: "bollicine",
  },
  {
    id: "bolla-cuvee-frati",
    name: "Cuvee dei Frati Metodo Classico",
    description: "Elegante bolla brut lombarda metodo classico, finezza perlage con sentori di mandorla tostata e lieviti.",
    price: 30.00,
    category: "bollicine",
  },
  {
    id: "bolla-w-heart-rose",
    name: "W'heart spumante rosato",
    description: "Spumante rosato fresco beverino ideale per brindisi festivi e per iniziare alla grande gli antipasti.",
    price: 16.00,
    category: "bollicine",
  },
  {
    id: "bolla-franciacorta",
    name: "Franciacorta Saten",
    description: "Spumante saten morbido e setoso di altissima nobiltà delle cantine bresciane.",
    price: 40.00,
    category: "bollicine",
    tags: ["Saten"],
  },
  {
    id: "bolla-akenta-vermentino",
    name: "Akenta vermentino spumante",
    description: "Splendido spumante extra dry di vermentino sardo doc, brioso floreale.",
    price: 22.00,
    category: "bollicine",
  },
  {
    id: "bolla-w-heart-white",
    name: "W' heart extra dry",
    description: "Spumante extra dry persistente, bollicina finissima sapida beverino.",
    price: 16.00,
    category: "bollicine",
  },

  // PANINI GOURMET
  {
    id: "panino-provolone",
    name: "Provolone con contorno di patatine fritte",
    description: "Bun artigianale caldissimo, Hamburger di scottona da 250g, provolone ruspante scottato alla brace, dolce cipolla caramellata, mais dolce, pancetta arrotolata, pomodoro fresco, pesto di rucola foggiana e noci. Accompagnato da patatine fritte dorate.",
    price: 11.00,
    category: "panini",
    tags: ["Panino Best Seller"],
  },
  {
    id: "panino-pollo",
    name: "Il pollo con contorno di patatine fritte",
    description: "Saporitissimo panino gourmet con morbido pollo panato croccante speziato al curry, fette di pomodoro, lattuga iceberg, cipolla caramellata profumata e salsa chili piccante. Servito con patatone fritte dorate.",
    price: 10.00,
    category: "panini",
  },
  {
    id: "panino-porcino",
    name: "Porcino con contorno di patatine fritte",
    description: "Incontro sublime: Bun tostato, Hamburger di scottona 250g, bacon affumicato croccante, pomodorini confit caramellati, cremosa burrata ai funghi porcini caldi, pesto fresco di basilico genovese e pinoli tostate. Accompagnato da patatine fritte.",
    price: 11.00,
    category: "panini",
    tags: ["Gourmet Burger"],
  },
  {
    id: "panino-1661",
    name: "1661 con contorno di patatine fritte",
    description: "Omaggio di gusto: Mortadella Bologna IGP scottata, pesto di pistacchi di Bronte, lattiginosa stracciatella di bufala foggiana e pomodori secchi saporiti pugliesi sott'olio. Servito con fritte.",
    price: 11.00,
    category: "panini",
    tags: ["Consigliatissimo"],
  },

  // LE PAZZIE DEL NATALE
  {
    id: "natale-fritte-prosecco",
    name: "Pizze fritte più bottiglia prosecco",
    description: "La super festa della vigilia foggiana: un intero kg delle nostre caldissime e soffici pizze fritte tradizionali vuote abbinate ad una fredda bottiglia intera di ottimo spumante prosecco brut DOC.",
    price: 20.00,
    category: "pazzie-natale",
    tags: ["Vigilia Foggiana"],
  },
  {
    id: "natale-fritte-kg",
    name: "Pizze fritte un kg",
    description: "Tradizione pura al pezzo: un chilogrammo completo di deliziose e sofficissime pizze fritte della tradizione foggiana, fatte a mano fragranti e bollenti.",
    price: 10.00,
    category: "pazzie-natale",
  },
  {
    id: "natale-prosecco",
    name: "Bottiglia di prosecco",
    description: "Bottiglia intera ghiacciata di prosecco millesimato brut DOC d'accompagnamento.",
    price: 10.00,
    category: "pazzie-natale",
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    author: "Gianluca M.",
    rating: 5,
    text: "La migliore pizza al metro di Foggia senza ombra di dubbio! L'impasto di Da Antonello ha una leggerezza incredibile, soffice e digeribile anche il giorno dopo. Abbiamo preso il metro misto (Margherita, Garganica e Foggiana) ed era favoloso. Servizio di asporto organizzato alla perfezione via WhatsApp. Top!",
    date: "2026-06-10",
    location: "Foggia",
    isVerified: true
  },
  {
    id: "rev-2",
    author: "Maria Teresa S.",
    rating: 5,
    text: "Pizzeria fantastica in zona via Giuseppe De Petra. Abbiamo prenotato un tavolo per il weekend proprio da qui e siamo rimasti estremamente felici. La pizza gourmet con prosciutto 24 mesi e burrata fatta a crudo è un capolavoro. Torneremo sicuramente! I proprietari Antonello e lo staff sono persone squisite.",
    date: "2026-06-08",
    location: "Foggia",
    isVerified: true
  },
  {
    id: "rev-3",
    author: "Michele D.",
    rating: 5,
    text: "Ho provato la consegna a domicilio tramite WhatsApp ieri sera. Temevo arrivasse fredda come capita spesso, invece la pizza al metro è arrivata caldissima, fragrante e puntuale. I panzerottini fritti sono asciutti e squisiti. Una garanzia per chi vive a Foggia e vuole mangiare pizza di alta classe a casa propria.",
    date: "2026-06-05",
    location: "Foggia",
    isVerified: true
  },
  {
    id: "rev-4",
    author: "Alessandra P.",
    rating: 4,
    text: "Ottima pizza, digeribile e con ingredienti chiaramente pugliesi ed eccellenti. La pizza al metro è una vera chicca, ti consente di assaggiare diversi gusti. Molto comodo il link per ordinare subito via WhatsApp. Cinque stelle meritatissime per l'impasto a lungia lievitazione!",
    date: "2026-05-28",
    location: "Lucera",
    isVerified: true
  }
];

export const RESTAURANT_INFO = {
  name: "Da Antonello",
  brand: "Da Antonello - Pizza al Metro & Pizzeria Artigianale",
  address: "Via Giuseppe De Petra, 7",
  city: "Foggia",
  postalCode: "71122",
  region: "FG, Puglia",
  country: "Italia",
  phone: "+39 377 082 4589", // Official or highly realistic WhatsApp phone number
  email: "info@da-antonello-foggia.it",
  openingHours: "Martedì - Domenica: 19:00 - 00:00 (Lunedì Chiuso)",
  mapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3000.3239247657973!2d15.548777!3d41.458925!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x133724c9c1b9b94d%3A0xe6bf446db9cb16dd!2sPizzeria%20Da%20Antonello!5e0!3m2!1sit!2sit!4v1700000000000!5m2!1sit!2sit",
  whatsappUrl: "https://wa.me/393770824589", // prefilled template base
  vatNumber: "IT04128530711" // real business representation
};
